services:
  carvedrock.api:
    image: ${DOCKER_REGISTRY-}carvedrockapi
    build:
      context: .
      dockerfile: CarvedRock.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - SeqAddress=http://seq:5341
      - ConnectionStrings__CarvedRockPostgres=Host=pgdb;Port=5432;Database=carvedrock;Username=postgres;Password=C0nt*inersAreGREAT!;
    ports:
      - '8080'
      - '8081'
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/https:/home/app/.aspnet/https:ro

  carvedrock.webapp:
    image: ${DOCKER_REGISTRY-}carvedrockwebapp
    build:
      context: .
      dockerfile: CarvedRock.WebApp/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - SeqAddress=http://seq:5341
      - CarvedRock__ApiBaseUrl=http://carvedrock.api:8080
    ports:
      - '8080'
      - '8081'
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/https:/home/app/.aspnet/https:ro

  seq:
    image: datalust/seq:latest
    ports:
      - '5330:80'
    environment:
      - ACCEPT_EULA=Y

  pgdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=C0nt*inersAreGREAT!
    ports:
      - '5444:5432'

  smtp4dev:
    image: rnwood/smtp4dev
    restart: always
    ports:
      - '5010:80'
